// Code generated by protoc-gen-go.
// source: rpc/proto/ra.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	rpc/proto/ra.proto
	rpc/proto/va.proto

It has these top-level messages:
	Domain
	Valid
	PerformValidationRequest
	VAChallenge
	KeyAuthorization
	AuthzMeta
	ValidationRecords
	ValidationRecord
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

var fileDescriptor0 = []byte{
	// 49 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2a, 0x48, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x4a, 0xd4, 0x03, 0x33, 0x84, 0x58, 0xc1, 0x54, 0x12,
	0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xdf, 0x47, 0xae, 0x23, 0x00, 0x00,
	0x00,
}
